---
- name: learning playbook
  hosts: all
  remote_user: devops
  become: yes
  vars_files:
    - myvars.yml
  tasks:
  - name: Include a file to setuphttpd
    include_tasks: /root/Ansible/installapache.yml

  - name: Include a file to setuphttpd
    include_tasks: /root/Ansible/servicehttp.yml

  - name: Include a file to setuphttpd
    include_tasks: /root/Ansible/firewallservice.yml
