---
- name: learning playbook
  hosts: all
  remote_user: devops
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: "{{ item }}"
      state: latest
    tags: taginstall
    with_items:
      - httpd
      - mariadb-5.5.60-1.el7_5.x86_64 

  - name: service status
    service:
      name: "{{ item }}"
      state: restarted 
    tags: tagservice
    with_items:
      - httpd
      - mariadb 

  - name: firewall status
    firewalld:
      port: "{{ item }}" 
      state: enabled
      permanent: true
      immediate: yes
    tags: tagfirewall
    with_items:
      - 80/tcp
      - 3306/tcp
