---
- name: learning playbook
  hosts: all
  remote_user: devops
  become: yes
  vars_files:
    - vars/secret.yml
  tasks:
  - name: create users from seeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecret.yml
    user: 
      name: "{{ item.name }}"
      password: "{{ item.pw | password_hash('sha512') }} "
      state: present
    with_items: "{{ newusers }}"
      
